name: deploy

on:
  push:
    branches:
      - main

jobs:
  vulns:
    name: Vulnerability scanner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - name: WriteGoList
        run: cd app/ && go list -json -m all > ../go.list
      - name: Nancy
        uses: sonatype-nexus-community/nancy-github-action@main

  golangci:
    needs: vulns
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest]
    name: test
    runs-on: ${{ matrix.os }}
    steps:
      - name: testing
        run: cd .. && pwd && ls && go test ./...

  build:
    needs: golangci
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          sync: true
          command_timeout: 3m
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          port: ${{ secrets.PROD_SSH_PORT }}
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PROD_SSH_PASS }}
          script: |
            cd ${{ secrets.PROD_DEPLOY_DIR }}
            git pull origin main && 
            docker-compose restart && 
            docker container exec go_server rm ./viet_college_api
            docker container exec go_server go build -ldflags "-s -w" -o . && 
            docker container exec go_server goupx viet_college_api &&
            docker container exec go_server goose -env production up &&
            docker container exec go_server ./viet_college_api &!
            exit